workflows:
  my-workflow:
    max_build_duration: 120
    scripts:
      - name: download ipsw
        script: wget http://updates-http.cdn-apple.com/2021WinterFCS/fullrestores/071-22729/77571761-8A7F-4F67-BB19-12D9BC82405B/iPhone11,2,iPhone11,4,iPhone11,6,iPhone12,3,iPhone12,5_14.4.2_18D70_Restore.ipsw
      - name: unzip
        script: unzip *.ipsw
      - name: Build
        script: python3 -/cloneios_install.py
    artifacts:
      - tools/*.ipa
